name: build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest] # Darwin only
        nim:
          - "stable"
          - "devel"
          - "2.0.x"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache choosenim
        uses: actions/cache@v4
        with:
          path: ~/.choosenim
          key: ${{ runner.os }}-choosenim-${{ matrix.nim }}

      - name: Cache nimble
        uses: actions/cache@v4
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
          restore-keys: |
            ${{ runner.os }}-nimble-

      - name: Install Nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: ${{ matrix.nim }}

      - name: Build
        run: |
          nimble check
          nimble build -y --gc:orc -d:release

      - name: Test
        run: |
          nimble test -y --gc:orc -d:release --debugger:native

      - name: Generate Coverage
        run: |
          nimble install -y coverage
          coverage ./tests/test_*.nim
        if: matrix.nim == 'stable'

      - name: Upload Coverage
        uses: codecov/codecov-action@v5.4.0
        with:
          files: ./coverage.out
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
        if: matrix.nim == 'stable'

      - name: Dry-run Release Build
        if: matrix.nim == 'stable'
        run: |
          mkdir -p dist
          cp ./darwinmetrics dist/
          cd dist && tar czf darwinmetrics-macos.tar.gz darwinmetrics
          shasum -a 256 darwinmetrics-macos.tar.gz > darwinmetrics-macos.tar.gz.sha256
          echo "✓ Release artifacts created successfully (dry-run)"
          ls -la
          cat darwinmetrics-macos.tar.gz.sha256
