name: Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        nim-version: ["2.2.2"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Cache choosenim
        id: cache-choosenim
        uses: actions/cache@v4
        with:
          path: ~/.choosenim
          key: ${{ runner.os }}-choosenim-${{ matrix.nim-version }}

      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v4
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ matrix.nim-version }}-${{ hashFiles('*.nimble') }}
          restore-keys: |
            ${{ runner.os }}-nimble-${{ matrix.nim-version }}-

      - name: Setup Nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: ${{ matrix.nim-version }}

      - name: Build
        run: nimble build -y

      - name: Test
        run: nimble test -y

      - name: Generate coverage
        if: matrix.nim-version == '2.2.2'
        run: |
          nimble coverage

      - name: Upload coverage
        if: matrix.nim-version == '2.2.2'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/*.xml
          fail_ci_if_error: true
