name: CI/CD

on:
  push:
    branches: [main, develop]
    tags: ["v*"]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
    inputs:
      create_release:
        description: "Create release"
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        nim-version: ["2.2.2"]
        include:
          - nim-version: "2.2.2"
            is-release: ${{ startsWith(github.ref, 'refs/tags/v') || github.event.inputs.create_release == 'true' }}

    steps:
      - uses: actions/checkout@v4

      - name: Cache Nim environment
        uses: actions/cache@v4
        with:
          path: |
            ~/.choosenim
            ~/.nimble
          key: ${{ runner.os }}-nim-${{ matrix.nim-version }}-${{ hashFiles('*.nimble') }}
          restore-keys: |
            ${{ runner.os }}-nim-${{ matrix.nim-version }}-
            ${{ runner.os }}-nim-

      - name: Setup Nim
        uses: jiro4989/setup-nim-action@v2.2.2
        with:
          nim-version: ${{ matrix.nim-version }}

      - name: Install Dependencies
        run: |
          nimble refresh
          nimble install -y --verbose
          nimble develop -y

      - name: Build & Test
        run: |
          nimble test -d:noThreads -y --verbose

      - name: Prepare Release Assets
        if: matrix.is-release
        run: |
          mkdir -p dist
          # Create a source distribution
          git archive --format=tar.gz --prefix=darwinmetrics-${{ github.ref_name }}/ -o dist/darwinmetrics-${{ github.ref_name }}.tar.gz HEAD
          cd dist
          shasum -a 256 darwinmetrics-${{ github.ref_name }}.tar.gz > darwinmetrics-${{ github.ref_name }}.tar.gz.sha256

      - name: Create Release
        if: matrix.is-release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/darwinmetrics-${{ github.ref_name }}.tar.gz
            dist/darwinmetrics-${{ github.ref_name }}.tar.gz.sha256
          generate_release_notes: true
          draft: true
